# Generated by Django 5.2 on 2025-04-26 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0002_table_qr_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitem',
            name='translations',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
