# Generated by Django 5.2 on 2025-05-01 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0006_alter_notification_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='statut',
            field=models.CharField(choices=[('nouvelle', 'Nouvelle'), ('preparation', 'En préparation'), ('prete', 'Prête'), ('servie', 'Servie')], default='nouvelle', max_length=20),
        ),
    ]
