# Generated by Django 5.2 on 2025-05-03 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0007_orderitem_statut'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('nouvelle', 'Nouvelle'), ('preparation', 'En préparation'), ('prete', 'Prête'), ('servie', 'Servie')], default='nouvelle', max_length=20),
        ),
    ]
