# Generated by Django 5.2 on 2025-05-12 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0008_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='table',
            name='session_key',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('nouvelle', 'Nouvelle'), ('preparation', 'En préparation'), ('prete', 'Prête'), ('servie', 'Servie'), ('annulee', 'Annulée')], default='nouvelle', max_length=20),
        ),
    ]
