# Generated by Django 5.2 on 2025-05-16 13:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0012_alter_order_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='is_sent',
            new_name='is_paid',
        ),
    ]
