# Generated by Django 5.2 on 2025-05-16 15:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0013_rename_is_sent_order_is_paid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notification',
            old_name='is_seen',
            new_name='is_paid',
        ),
    ]
