# Generated by Django 5.2.1 on 2025-05-19 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0014_rename_is_seen_notification_is_paid'),
    ]

    operations = [
        migrations.AddField(
            model_name='cuisinier',
            name='is_online',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='serveur',
            name='is_online',
            field=models.BooleanField(default=False),
        ),
    ]
