# Generated by Django 5.2.1 on 2025-05-19 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0015_cuisinier_is_online_serveur_is_online'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('en_attente_serveur', 'En attente serveur'), ('nouvelle', 'Nouvelle'), ('preparation', 'En préparation'), ('prete', 'Prête'), ('servie', 'Servie')], default='en_attente_serveur', max_length=20),
        ),
    ]
