# Generated by Django 5.2.1 on 2025-05-22 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0016_alter_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('en_attente_serveur', 'En attente serveur'), ('nouvelle', 'Nouvelle'), ('preparation', 'En préparation'), ('prete', 'Prête'), ('servie', 'Servie'), ('annulee', 'Annulée')], default='en_attente_serveur', max_length=20),
        ),
    ]
