# Generated by Django 5.2.1 on 2025-06-03 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0018_order_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='prix_total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
    ]
