# Generated by Django 5.2.1 on 2025-06-20 23:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0020_notification_is_seen'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='table',
            name='session_key',
        ),
    ]
