# Generated by Django 5.2.1 on 2025-06-20 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0021_remove_table_session_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='table',
            name='session_key',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
    ]
